angular.module('tspApp').constant('theEvent', {
    "Title": "Supervise loading operations",
    "CommunityMosCode": "0431",
    "TempCommunityMosCode": "",
    "CommunityName": "Logistics",
    "LevelCode": "2",
    "TempLevelCode": "",
    "IsECoded": false,
    "Description": "",
    "Condition": "Given cargo, equipment, and personnel to be loaded,  required conveyance, load plans and required MHE.",
    "EventCode": "INDIV",
    "EventId": "{412FFAFC-E90B-C85C-E040-A8C02A162DC2}",
    "EventNumber": "0431-OPS-2702",
    "FunctionalAreaId": "8099132A-8F5E-4EC3-BFCE-51014F41ECD4",
    "TempFunctionalAreaId": "",
    "InitTrainSetCode": "MOJT",
    "SequenceNumber": "702",
    "Standard": "To ensure all assets and personnel are moved safely and efficiently.",
    "SustainmentInterval": 12,
    "RejectionReason": null,
    "Range": 'This is the range',
    "Aircraft": 'Some aircraft',
    "Simulation": 'some simulation',
    "Rooms": 'some rooms',
    "Equipment": 'some equipmrent',
    "Material": 'some material',
    "UnitsAndPersonnel": 'some units',
    "OtherSupportingRequirements": 'some other supoprting req',
    "AdministrativeInstructions": 'some admin instructions',
    "RoadMiles": null,
    "EquipmentHours": 'some equip hours',
    "SpecialPersonnelCerts": null,
    "Ordnance": 'some other ordnance',
    "Ranges": [],
    "References": [
        {
            "PublicationID": "CFR 49",
            "Title": "Code of Federal Regulations - Hazardous Materials"
        },
        {
            "PublicationID": "COMNAVSURFLANTINST 3000.3",
            "Title": "Landing Force Spaces and Material Aboard COMNAVSURFLANT Ships"
        },
        {
            "PublicationID": "COMNAVSURFLANTINST 3340.3 C",
            "Title": "Wet Well Operations Manual"
        },
        {
            "PublicationID": "DOD 4500.9-R",
            "Title": "Defense Transportation Regulation Parts I, II & III"
        },
        {
            "PublicationID": "FMFM 1-5",
            "Title": "Maritime Prepositioning Force (MPF) OPS"
        },
        {
            "PublicationID": "JOINT PUB 3-02.2",
            "Title": "Joint Doctrine for Amphibious Embarkation"
        },
        {
            "PublicationID": "MCRP 4-11C",
            "Title": "Combat Cargo Operations Handbook"
        }
    ],
    "PerformanceSteps": [
        {
            "PerformanceStepId": "{412FFAFC-EC29-C85C-E040-A8C02A162DC2}",
            "Title": "Coordinate the use of equipment at the port facility.",
            "ListPosition": 2
        },
        {
            "PerformanceStepId": "{412FFAFC-EC2A-C85C-E040-A8C02A162DC2}",
            "Title": "Coordinate the movement of cargo, equipment, and personnel from the applicable staging areas to the loading area.",
            "ListPosition": 3
        },
        {
            "PerformanceStepId": "{412FFAFC-EC2B-C85C-E040-A8C02A162DC2}",
            "Title": "Monitor the embarkation and stowage of cargo and equipment.",
            "ListPosition": 4
        },
        {
            "PerformanceStepId": "{412FFAFC-EC2C-C85C-E040-A8C02A162DC2}",
            "Title": "Compute the estimate of time to complete loading operations.",
            "ListPosition": 5
        },
        {
            "PerformanceStepId": "{412FFAFC-EC2D-C85C-E040-A8C02A162DC2}",
            "Title": "Prepare and submit loading reports, as required.",
            "ListPosition": 6
        },
        {
            "PerformanceStepId": "{412FFAFC-EC28-C85C-E040-A8C02A162DC2}",
            "Title": "Determine supporting supply, equipment, and personnel requirements.",
            "ListPosition": 1
        }
    ],
    "PreReqEvents": [
        {
            "_IsECoded": "N",
            "_IsCrpRelated": "N",
            "_IsFormalEvent": "N",
            "CreatedBy": "",
            "CreatedDate": "0001-01-01T00:00:00",
            "EditedBy": "",
            "EditedDate": "0001-01-01T00:00:00",
            "inUse": null,
            "GenomeApprovedEventCode": "",
            "ShowChained": true,
            "ShowRelated": true,
            "ShowExtSupported": false,
            "ShowExtSupporting": false,
            "ShowIntSupporting": false,
            "ShowIntSupported": false,
            "LevelText": "4000",
            "OwnerCommunityId": "938ED488-A7DF-4686-A786-4FBB057E8B28",
            "LinkedBy": null,
            "OwnerCommunityTitle": "Logistics",
            "InUse": "No",
            "InitTrainSetText": "",
            "CorePlusText": "CORE",
            "EventId": "{412FFAFC-E8FC-C85C-E040-A8C02A162DC2}",
            "CommunityName": "Logistics",
            "PrimarySimCodeName": "",
            "Title": "Conduct Air Movement",
            "TitleWithoutSim": "Conduct Air Movement",
            "CommunityMosCode": "LOG",
            "TempCommunityMosCode": "",
            "CommunityOrMOSCode": "LOG",
            "FunctionalAreaId": "{1440f00f-60f2-48b0-901e-58f375f07bc1}",
            "TempFunctionalAreaId": "",
            "LevelCode": "4",
            "TempLevelCode": "",
            "SequenceNumber": "301",
            "TempSequenceNumber": "",
            "FormattedEventCode": "LOG-EXCU-4301",
            "TempFormattedEventCode": "--",
            "EventCode": "COLLECT",
            "InitTrainSetCode": "",
            "Description": "",
            "CorePlusCode": "CORE",
            "IsECoded": "N",
            "IsECodedBool": false,
            "IsCrpRelated": "N",
            "IsCrpRelatedBool": false,
            "IsFormalEvent": "N",
            "IsFormalEventBool": false,
            "SustainmentInterval": 12,
            "Condition": "Given deployment data, internet connectivity, and AIS",
            "Standard": "To ensure all requirements move via the assigned aircraft.",
            "FunctionalArea": null,
            "FunctionalAreaCode": "EXCU",
            "TempFunctionalAreaCode": "",
            "EventStatusText": "Archived",
            "EventStatus": {
                "code": 5
            },
            "GenomeId": "{DED29AC6-2B56-305E-E043-0100007F8428}",
            "PlannedForArchival": "No",
            "EventNumber": "LOG-EXCU-4301",
            "AuditCreatedBy": "",
            "AuditCreatedDate": "0001-01-01T00:00:00",
            "AuditEditedBy": "",
            "AuditEditedDate": "0001-01-01T00:00:00",
            "IsValid": true,
            "EventType": "New"
        },
        {
            "_IsECoded": "Y",
            "_IsCrpRelated": "N",
            "_IsFormalEvent": "N",
            "CreatedBy": "",
            "CreatedDate": "0001-01-01T00:00:00",
            "EditedBy": "",
            "EditedDate": "0001-01-01T00:00:00",
            "inUse": null,
            "GenomeApprovedEventCode": "",
            "ShowChained": true,
            "ShowRelated": true,
            "ShowExtSupported": false,
            "ShowExtSupporting": false,
            "ShowIntSupporting": false,
            "ShowIntSupported": false,
            "LevelText": "4000",
            "OwnerCommunityId": "938ED488-A7DF-4686-A786-4FBB057E8B28",
            "LinkedBy": null,
            "OwnerCommunityTitle": "Logistics",
            "InUse": "No",
            "InitTrainSetText": "",
            "CorePlusText": "CORE",
            "EventId": "{412FFAFC-E992-C85C-E040-A8C02A162DC2}",
            "CommunityName": "Logistics",
            "PrimarySimCodeName": "",
            "Title": "Conduct Commercial Vessel Embarkation",
            "TitleWithoutSim": "Conduct Commercial Vessel Embarkation",
            "CommunityMosCode": "LOG",
            "TempCommunityMosCode": "",
            "CommunityOrMOSCode": "LOG",
            "FunctionalAreaId": "{1440f00f-60f2-48b0-901e-58f375f07bc1}",
            "TempFunctionalAreaId": "",
            "LevelCode": "4",
            "TempLevelCode": "",
            "SequenceNumber": "303",
            "TempSequenceNumber": "",
            "FormattedEventCode": "LOG-EXCU-4303",
            "TempFormattedEventCode": "--",
            "EventCode": "COLLECT",
            "InitTrainSetCode": "",
            "Description": "",
            "CorePlusCode": "CORE",
            "IsECoded": "Y",
            "IsECodedBool": true,
            "IsCrpRelated": "N",
            "IsCrpRelatedBool": false,
            "IsFormalEvent": "N",
            "IsFormalEventBool": false,
            "SustainmentInterval": 12,
            "Condition": "Given deployment data, internet connectivity, ship load-planning AIS,",
            "Standard": "To ensure 100% accountability IAW BALS.",
            "FunctionalArea": null,
            "FunctionalAreaCode": "EXCU",
            "TempFunctionalAreaCode": "",
            "EventStatusText": "Archived",
            "EventStatus": {
                "code": 5
            },
            "GenomeId": "{DED29AC6-205B-305E-E043-0100007F8428}",
            "PlannedForArchival": "No",
            "EventNumber": "LOG-EXCU-4303",
            "AuditCreatedBy": "",
            "AuditCreatedDate": "0001-01-01T00:00:00",
            "AuditEditedBy": "",
            "AuditEditedDate": "0001-01-01T00:00:00",
            "IsValid": true,
            "EventType": "New"
        },
        {
            "_IsECoded": "Y",
            "_IsCrpRelated": "N",
            "_IsFormalEvent": "N",
            "CreatedBy": "",
            "CreatedDate": "0001-01-01T00:00:00",
            "EditedBy": "",
            "EditedDate": "0001-01-01T00:00:00",
            "inUse": null,
            "GenomeApprovedEventCode": "",
            "ShowChained": true,
            "ShowRelated": true,
            "ShowExtSupported": false,
            "ShowExtSupporting": false,
            "ShowIntSupporting": false,
            "ShowIntSupported": false,
            "LevelText": "4000",
            "OwnerCommunityId": "938ED488-A7DF-4686-A786-4FBB057E8B28",
            "LinkedBy": null,
            "OwnerCommunityTitle": "Logistics",
            "InUse": "No",
            "InitTrainSetText": "",
            "CorePlusText": "CORE",
            "EventId": "{412FFAFC-E943-C85C-E040-A8C02A162DC2}",
            "CommunityName": "Logistics",
            "PrimarySimCodeName": "",
            "Title": "Conduct Amphibious Embarkation",
            "TitleWithoutSim": "Conduct Amphibious Embarkation",
            "CommunityMosCode": "LOG",
            "TempCommunityMosCode": "",
            "CommunityOrMOSCode": "LOG",
            "FunctionalAreaId": "{1440f00f-60f2-48b0-901e-58f375f07bc1}",
            "TempFunctionalAreaId": "",
            "LevelCode": "4",
            "TempLevelCode": "",
            "SequenceNumber": "302",
            "TempSequenceNumber": "",
            "FormattedEventCode": "LOG-EXCU-4302",
            "TempFormattedEventCode": "--",
            "EventCode": "COLLECT",
            "InitTrainSetCode": "",
            "Description": "",
            "CorePlusCode": "CORE",
            "IsECoded": "Y",
            "IsECodedBool": true,
            "IsCrpRelated": "N",
            "IsCrpRelatedBool": false,
            "IsFormalEvent": "N",
            "IsFormalEventBool": false,
            "SustainmentInterval": 12,
            "Condition": "Given deployment data, internet connectivity, ship load-planning AIS,",
            "Standard": "To ensure 100% accountability IAW BALS.",
            "FunctionalArea": null,
            "FunctionalAreaCode": "EXCU",
            "TempFunctionalAreaCode": "",
            "EventStatusText": "Archived",
            "EventStatus": {
                "code": 5
            },
            "GenomeId": "{DED29AC6-558A-305E-E043-0100007F8428}",
            "PlannedForArchival": "No",
            "EventNumber": "LOG-EXCU-4302",
            "AuditCreatedBy": "",
            "AuditCreatedDate": "0001-01-01T00:00:00",
            "AuditEditedBy": "",
            "AuditEditedDate": "0001-01-01T00:00:00",
            "IsValid": true,
            "EventType": "New"
        },
        {
            "_IsECoded": "Y",
            "_IsCrpRelated": "N",
            "_IsFormalEvent": "N",
            "CreatedBy": "",
            "CreatedDate": "0001-01-01T00:00:00",
            "EditedBy": "",
            "EditedDate": "0001-01-01T00:00:00",
            "inUse": null,
            "GenomeApprovedEventCode": "",
            "ShowChained": true,
            "ShowRelated": true,
            "ShowExtSupported": false,
            "ShowExtSupporting": false,
            "ShowIntSupporting": false,
            "ShowIntSupported": false,
            "LevelText": "3000",
            "OwnerCommunityId": "938ED488-A7DF-4686-A786-4FBB057E8B28",
            "LinkedBy": null,
            "OwnerCommunityTitle": "Logistics",
            "InUse": "No",
            "InitTrainSetText": "",
            "CorePlusText": "CORE",
            "EventId": "{412FFAFC-E945-C85C-E040-A8C02A162DC2}",
            "CommunityName": "Logistics",
            "PrimarySimCodeName": "",
            "Title": "Conduct Movement to Port of Embarkation",
            "TitleWithoutSim": "Conduct Movement to Port of Embarkation",
            "CommunityMosCode": "LOG",
            "TempCommunityMosCode": "",
            "CommunityOrMOSCode": "LOG",
            "FunctionalAreaId": "{1440f00f-60f2-48b0-901e-58f375f07bc1}",
            "TempFunctionalAreaId": "",
            "LevelCode": "3",
            "TempLevelCode": "",
            "SequenceNumber": "302",
            "TempSequenceNumber": "",
            "FormattedEventCode": "LOG-EXCU-3302",
            "TempFormattedEventCode": "--",
            "EventCode": "COLLECT",
            "InitTrainSetCode": "",
            "Description": "",
            "CorePlusCode": "CORE",
            "IsECoded": "Y",
            "IsECodedBool": true,
            "IsCrpRelated": "N",
            "IsCrpRelatedBool": false,
            "IsFormalEvent": "N",
            "IsFormalEventBool": false,
            "SustainmentInterval": 12,
            "Condition": "Given supplies & equipment, movement schedule, DOD-ITV access.",
            "Standard": "To ensure 100% accountability & combat readiness.",
            "FunctionalArea": null,
            "FunctionalAreaCode": "EXCU",
            "TempFunctionalAreaCode": "",
            "EventStatusText": "Archived",
            "EventStatus": {
                "code": 5
            },
            "GenomeId": "{DED29AC6-3032-305E-E043-0100007F8428}",
            "PlannedForArchival": "No",
            "EventNumber": "LOG-EXCU-3302",
            "AuditCreatedBy": "",
            "AuditCreatedDate": "0001-01-01T00:00:00",
            "AuditEditedBy": "",
            "AuditEditedDate": "0001-01-01T00:00:00",
            "IsValid": true,
            "EventType": "New"
        }
    ]
});
